### ISSUE TITLE
reverse proxy for webui not connecting

### ISSUE THREAD

**Issue by compleatang** [protocol/ipfs-webui#4]
we are running an ipfs gateway on a server.

i'd like to be able to run the API behind a reverse proxy so that we can add basic authentication for the node but expose the gateway to the public. also, i'd like the url to resolve without having to type the ports when i want to check the gateway.

setup: ipfs with API on `0.0.0.0:5001` nginx in front reverse proxying to `ipfsc.erisbootstrap.sexy` ... nginx is working properly for the gateway (see #3 ) and urls to ipfs.erisbootstrap.sexy (which is routed to the gateway port) all resolve fine.

problem: when i connect to ipfsc.erisbootstrap.sexy which is proxied to 5001, the webui loads fine but does not connect to the API properly. it is just a plain UI without any connection details. however when I connect via the IP:Port combo it resolves fine. links below:

* url i'd like to use which won't connect to the api on the node: https://ipfsc.erisbootstrap.sexy/webui
* url which i'm not keen to use which does connect to the api on the node: http://54.93.113.247:5001/webui

**Comment by travisperson** [comment]
This is due to `window.port` not being defined when not present in the URL, with an undefined port the ipfs-api module defaults to 5001. You can see these request failing in your web console.

Checking for an undefined port and setting it to 80 prior to initalizing the ipfs-api should fix this issue
